// <auto-generated />
using System;
using AlphaPMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlphaPMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlphaPmsDbContext))]
    partial class AlphaPmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AlphaPMS.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("budget");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("FinishDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("finish_date");

                    b.Property<string>("Investor")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("investor");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_visible");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("manager");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("ProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("progress_percent");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_code");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("AlphaPMS.Domain.Projects.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("dependency_type");

                    b.Property<int>("LagDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lag_days");

                    b.Property<Guid>("PredecessorTaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("predecessor_task_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<Guid>("SuccessorTaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("successor_task_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PredecessorTaskId")
                        .HasDatabaseName("ix_task_dependencies_predecessor");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_task_dependencies_project_id");

                    b.HasIndex("SuccessorTaskId")
                        .HasDatabaseName("ix_task_dependencies_successor");

                    b.HasIndex("ProjectId", "PredecessorTaskId", "SuccessorTaskId", "DependencyType")
                        .IsUnique()
                        .HasDatabaseName("ux_task_dependencies_relation");

                    b.ToTable("task_dependencies", (string)null);
                });

            modelBuilder.Entity("AlphaPMS.Domain.Projects.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration");

                    b.Property<DateOnly?>("FinishDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("finish_date");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_type");

                    b.Property<decimal?>("MachineShiftFactor")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_shift_factor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal?>("Nclm")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("nclm");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_id");

                    b.Property<decimal?>("PermanentLabor")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("permanent_labor");

                    b.Property<decimal>("ProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("progress_percent");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_work_items_parent_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_work_items_project_id");

                    b.HasIndex("ProjectId", "ParentId", "SortOrder")
                        .HasDatabaseName("ix_work_items_project_parent_sort");

                    b.ToTable("work_items", (string)null);
                });

            modelBuilder.Entity("AlphaPMS.Domain.Projects.TaskDependency", b =>
                {
                    b.HasOne("AlphaPMS.Domain.Projects.WorkItem", "PredecessorTask")
                        .WithMany()
                        .HasForeignKey("PredecessorTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlphaPMS.Domain.Projects.Project", "Project")
                        .WithMany("TaskDependencies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaPMS.Domain.Projects.WorkItem", "SuccessorTask")
                        .WithMany()
                        .HasForeignKey("SuccessorTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PredecessorTask");

                    b.Navigation("Project");

                    b.Navigation("SuccessorTask");
                });

            modelBuilder.Entity("AlphaPMS.Domain.Projects.WorkItem", b =>
                {
                    b.HasOne("AlphaPMS.Domain.Projects.WorkItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlphaPMS.Domain.Projects.Project", "Project")
                        .WithMany("WorkItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AlphaPMS.Domain.Projects.Project", b =>
                {
                    b.Navigation("TaskDependencies");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("AlphaPMS.Domain.Projects.WorkItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
